### ISSUE TITLE
Question about interpreting probe metrics

### ISSUE THREAD

**Issue by junzeye** [belindal/state-probes#1]
Hi Belinda!

I am a student from Princeton, and a couple friends and I are trying to reproduce results of your [2021 paper](https://aclanthology.org/2021.acl-long.143/) as part of a class project. We encountered two questions regarding the output of `scripts/print_metrics.py`, and would really appreciate some clarifications:

1. When we printed evaluation metrics of the probes specified in Table 1, the output showed two kinds of metrics: "All queried results" and "All full results" (see screenshot below, showing results my team got from evaluating a `t5` probe finetuned on `textWorld` and localized to `first`). Do you mind clarifying what's the difference between how State EM was calculated in the two kinds of results?
2. Line 175 of [`scripts/print_metrics.py`](https://github.com/belindal/state-probes/blob/main/scripts/print_metrics.py) mentions the directory `state-probes-TW/tw_games`. After following instructions on the readme file to download data files, I couldn't find such a folder (the closest I could find is `tw_data`). Could you clarify what the former directory contains, and if the content is the same as the directory `tw_data`? When I ran `scripts/print_metrics.py`, I had to change the path `state-probes-TW/tw_games` to `tw_data` to get the program to run, and I wonder if this revision contributed to us getting zero for the State EM under "All full results".

Thank you in advance for your help!

Best,
Tony

<img width="1000" alt="Screen Shot 2022-04-27 at 17 43 53" src="https://user-images.githubusercontent.com/73705313/165636195-19a4b62d-68a0-4698-9c7b-aec1e6cec033.png">

**Comment by belindal** [comment]
Hi Tony,
1. "All queried results" is what's reported in Table 1. "All full results" refers to *all* facts in a situation over all pairs of entities in TextWorld. The fact that it is 0 here makes sense as in all situations, there will be entity pairs we cannot query (i.e. due to the entities not having been mentioned yet in the context). For the TextWorld domain, I would only focus on numbers reported in "All queried results".
2. Good catch! Yes, what was under `../state-probes-TW/tw_games` is now under `tw_data`. I'll fix the filepath names in the next version. 

The discrepancy between your results and the reported result could be due to a number of factors. For TextWorld, I trained the probe for many more epochs than the default setting. As a first pass, I would try setting `--epochs 100` and seeing if you get better probe accuracies.

Hope this helps!

**Comment by junzeye** [comment]
Thanks for the quick and helpful response, Belinda! I will try to change the epoch setting to see its effect on probe accuracies.

By the way, my project team is wondering if you have suggestions for additional ablation experiments of `T5` and `BART` to understand which part of the pretrained NLM architecture is mainly responsible for encoding semantic meaning.

For one, we have tried varying the number of layers and attention heads of a pretrained transformer model, but we got tensor dimensionality errors possibly due to a mismatch between pretrained model weights and the revised model. If there are other model hyperparameters potentially worth us tinkering with, please feel free to let me know!

Thanks again for your help!
